version: '3.8'

services:
  spring_api:
    build: .
    restart: always # restart automatiquement en cas d'erreur ou d'echec
    ports:
      - 8080:8080
    networks:
      - projetisi_springNetwork
    environment:
      - spring.datasource.url=jdbc:mysql://db:3306/projet_isi?createDatabaseIfNotExist=true
    depends_on:
      - db
    volumes:
      - .springVol:/root/.springVol
    #command: ["./wait-for-it.sh", "db:3306", "--", "java", "-jar", "app.jar"]

  db:
    image: "mysql:8.0"
    restart: always
    ports:
      - 3306:3306
    networks:
      - projetisi_springNetwork
    environment:
      MYSQL_DATABASE: projet_isi
      MYSQL_ALLOW_EMPTY_PASSWORD: 'true'
networks:
  projetisi_springNetwork:
      driver: bridge